version: '3.8'

services:
  # 1つ目のサービス：Webアプリケーション
  webapp:
    build: ./app-01-hello-flask
    container_name: hello-flask-app
    restart: always

  # 2つ目のサービス：テトリスゲーム
  tetris:
    build: ./app-02-tetris
    container_name: tetris-game
    restart: always

  # 3つ目のサービス：市区町村クイズ
  geogue-shikucho:
    build: ./app-03-geogue-shikucho
    container_name: geogue-shikucho
    restart: always

  # 4つ目のサービス：受付・交通整理係
  nginx:
    build: ./nginx
    container_name: reverse-proxy
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - webapp
