version: '3.8'

services:
  # 1つ目のサービス：Webアプリケーション
  webapp:
    build: ./app-01-hello-flask
    container_name: hello-flask-app
    restart: always

  # 2つ目のサービス：テトリスゲーム
  tetris:
    build: ./app-02-tetris
    container_name: tetris-game
    restart: always

  # 3つ目のサービス：受付・交通整理係
  nginx:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443" # HTTPS用の443番ポートを追加
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt # Certbotと証明書を共有
      - certbot-var:/var/lib/letsencrypt # Certbotと作業領域を共有
    restart: always
    depends_on:
      - webapp
      - tetris

  # 4つ目のサービス：証明書管理担当
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./app-01-hello-flask:/var/www/html # 証明書取得時の認証で使用
    depends_on:
      - nginx

# 証明書データを永続化するための共有スペースを定義
volumes:
  certbot-etc:
  certbot-var: